INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (1, 'Bilet 15-minutowy – na wszystkie linie', 'Normal', 3.20, 15, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (2, 'Bilet 15-minutowy – na wszystkie linie ulgowy', 'Discounted', 1.60, 15, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (3, 'Bilet 30-minutowy – na wszystkie linie', 'Normal', 4.00, 30, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (4, 'Bilet 30-minutowy – na wszystkie linie ulgowy', 'Discounted', 2.00, 30, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (5, 'Bilet 60-minutowy – na wszystkie linie', 'Normal', 5.20, 60, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (6, 'Bilet 60-minutowy – na wszystkie linie ulgowy', 'Discounted', 2.60, 60, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (7, 'Bilet 24-godzinny – na wszystkie linie', 'Normal', 15.00, 1440, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (8, 'Bilet 24-godzinny – na wszystkie linie ulgowy', 'Discounted', 7.50, 1440, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (9, 'Bilet jednorazowy – na wszystkie linie', 'Normal', 4.60, 9999999, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (10, 'Bilet jednorazowy – na wszystkie linie ulgowy', 'Discounted', 2.30, 9999999, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (11, 'Bilet 7-dniowy – na wszystkie linie', 'Normal', 38.00, 10080, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (12, 'Bilet 7-dniowy – na wszystkie linie ulgowy', 'Discounted', 19.00, 10080, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (13, 'Bilet 30-dniowy – na wszystkie linie', 'Normal', 110.00, 43200, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (14, 'Bilet 30-dniowy – na wszystkie linie ulgowy', 'Discounted', 55.00, 43200, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (15, 'Bilet 365-dniowy – na wszystkie linie', 'Normal', 1050.00, 525600, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (16, 'Bilet 365-dniowy – na wszystkie linie ulgowy', 'Discounted', 525.00, 525600, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (17, 'Bilet 30-dniowy „Nasz Wrocław” – na dwie dowolne linie', 'Normal', 60.00, 43200, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (18, 'Bilet 30-dniowy „Nasz Wrocław” – na dwie dowolne linie ulgowy', 'Discounted', 30.00, 43200, true);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (19, 'Bilet 365-dniowy „Nasz Wrocław” – na dwie dowolne linie', 'Normal', 800.00, 525600, false);
INSERT INTO public.ticket_types (id_ticket_type, name, type, price, validity_duration, is_discounted) VALUES (20, 'Bilet 365-dniowy „Nasz Wrocław” – na dwie dowolne linie ulgowy', 'Discounted', 400.00, 525600, true);
